from blood_analysis_hub import db, create_app
from blood_analysis_hub.models import Test, Attribute_list
from datetime import date
app = create_app()
app.app_context().push()

test = Test(title='lab 1', date_posted=date(2020, 1, 1), user_id=1)
db.session.add(test)
al = Attribute_list(test_id=1, attribute_id=1, value=2.5)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=2, value=43)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=3, value=4.5)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=4, value=90)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=5, value=0.4)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=6, value=4)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=7, value=7)
db.session.add(al)
al = Attribute_list(test_id=1, attribute_id=8, value=200)
db.session.add(al)
test = Test(title='lab 2', date_posted=date(2020, 6, 1), user_id=1)
db.session.add(test)
al = Attribute_list(test_id=2, attribute_id=1, value=3)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=2, value=40)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=3, value=5)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=4, value=75)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=5, value=0.47)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=6, value=4.2)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=7, value=9)
db.session.add(al)
al = Attribute_list(test_id=2, attribute_id=8, value=140)
db.session.add(al)
test = Test(title='lab 3', date_posted=date(2021, 1, 1), user_id=1)
db.session.add(test)
al = Attribute_list(test_id=3, attribute_id=1, value=3)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=2, value=40)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=3, value=5)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=4, value=75)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=5, value=0.47)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=6, value=4.2)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=7, value=9)
db.session.add(al)
al = Attribute_list(test_id=3, attribute_id=8, value=140)
db.session.add(al)
db.session.commit()
